apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-svc
  template:
    metadata:
      labels:
        app: hello-svc
    spec:
      containers:
      - name: hello-svc
        image: servantcode/hello-svc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
        env:
        - name: ES_JAVA_OPTS 
          value: "-Xmx128m -Xms128m"
        - name: DB_HOST
          value: "postgres"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-client-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-client-secrets
              key: db_password
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-key
              key: jwt-key
---
kind: Service
apiVersion: v1
metadata:
  name: hello-svc
spec:
  selector:
    app: hello-svc
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
